const SUCCESS = 200;
const CREATED = 201;
const BAD_REQUEST = 400;
const AUTH_FAIL = 401;
const SERVER_ERROR = 500;

const MESSAGE_SENT = "MESSAGE_SENT",
  RECEIVE_MESSAGE = "RECEIVE_MESSAGE",
  LAST_MESSAGE_UPDATE = "LAST_MESSAGE_UPDATE",
  MESSAGE_SENT_RECEIVED = "MESSAGE_SENT_RECEIVED",
  CONVERSATION_CHANGE = "CONVERSATION_CHANGE";

module.exports = {
  statusCode: {
    SUCCESS,
    CREATED,
    AUTH_FAIL,
    BAD_REQUEST,
    SERVER_ERROR,
  },
  event: {
    MESSAGE_SENT,
    MESSAGE_SENT_RECEIVED,
    RECEIVE_MESSAGE,
    LAST_MESSAGE_UPDATE,
    CONVERSATION_CHANGE,
  },
};
